### ISSUE TITLE
Doesn't compiles css

### ISSUE THREAD

**Issue by lavezzi1** [postcss/postcss-loader#106]
Hello! This is my config https://gist.github.com/lavezzi1/f7d10bd44462b089a97690c2591a340e

I got output files without any compilation, I got variables and things like `&__element` in the output css. No errors. What I did wrong?

**Comment by ai** [comment]
We still in webpack 2 support development. Did you use `postcss-loader` from master by `"postcss-loader": "postcss/postcss-loader"` in your `package.json`?

**Comment by ai** [comment]
Here is a discuss: https://github.com/postcss/postcss-loader/issues/99

We tried to fix webpack 2 support, change docs, but didn’t release it to npm yet (there are many changes, we need to check them first).

**Comment by lavezzi1** [comment]
@ai in my package.json I have "postcss-loader": "^0.13.0", "webpack": "^2.1.0-beta.19"

**Comment by ai** [comment]
0.13 has no webpack 2 support.

Could you help us and test postcss-loader from git master for webpack 2 support?

Here is discussion https://github.com/postcss/postcss-loader/pull/97

**Comment by lavezzi1** [comment]
@ai Its pleasure to help! So I changed version of "postcss-loader": "postcss/postcss-loader" but in my case it still doesnt works. Is my config correct?

**Comment by ai** [comment]
Hm. Could you try to move plugins to `postcss.config.js` (docs contains example).

**Comment by lavezzi1** [comment]
I created. Got a lot of errors, example: 
```
ERROR in /code/webpack2/ss2/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/code/webpack2/ss2/node_modules/vue-style-loader/index.js!/code/webpack2/ss2/node_modules/css-loader/index.js!/code/webpack2/ss2/node_modules/postcss-loader/index.js!/code/webpack2/ss2/node_modules/vue-loader/lib/style-rewriter.js!/code/webpack2/ss2/source/blocks/smart-table/smart-table-icon-has-status/style.css doesn't export content

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/postcss-loader!./~/vue-loader/lib/style-rewriter.js!./source/blocks/smart-table/smart-table-icon-title-caption/style.css
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/code/webpack2/ss2/loader-utils'
	Error: ENOENT: no such file or directory, open '/code/webpack2/ss2/loader-utils'
	    at Error (native)
	Error loading /code/webpack2/ss2/loader-utils as "loader-utils" from /code/webpack2/ss2/node_modules/extract-text-webpack-plugin/loader.js

ERROR in /code/webpack2/ss2/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/code/webpack2/ss2/node_modules/vue-style-loader/index.js!/code/webpack2/ss2/node_modules/css-loader/index.js!/code/webpack2/ss2/node_modules/postcss-loader/index.js!/code/webpack2/ss2/node_modules/vue-loader/lib/style-rewriter.js!/code/webpack2/ss2/source/blocks/table-icon-title-caption/style.css doesn't export content
```

**Comment by ai** [comment]
Could you show your webpack and PostCSS config?

**Comment by lavezzi1** [comment]
@ai webpack.config.js – https://gist.github.com/lavezzi1/089d4f561ba7604a1387de971878b3df
postcss.config.js https://gist.github.com/lavezzi1/f706711ad47813b5bff2ab6365b6c0aa

**Comment by ai** [comment]
You sets PostCSS plugins to `LoaderOptionsPlugin` abd to PostCSS config 😊.

Could you remove it from `LoaderOptionsPlugin`?

**Comment by ai** [comment]
And please set syntax in gist to syntax highlight.

**Comment by lavezzi1** [comment]
@ai oh my bad, I removed but still errors. And changed syntax.

**Comment by ai** [comment]
Maybe issue cane from vue loader? At least it is vue in stacktrace.

Could you test it without vue?

**Comment by lavezzi1** [comment]
@ai Take a look at this error:
```
ERROR in ./source/blocks/wizard-blocks/plan/style.css
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/code/webpack2/ss2/loader-utils'
	Error: ENOENT: no such file or directory, open '/code/webpack2/ss2/loader-utils'
	    at Error (native)
	Error loading /code/webpack2/ss2/loader-utils as "loader-utils" from /code/webpack2/ss2/node_modules/extract-text-webpack-plugin/loader.js
```
Why it imports from projects root directory instead of node_modules.

**Comment by ai** [comment]
Yeap, very strange. But I have no idea 😕.

**Comment by lavezzi1** [comment]
@ai I downgraded to postcss-import 8.0.2 and got another errors:
```
    ERROR in ./~/css-loader!./~/postcss-loader!./~/vue-loader/lib/style-rewriter.js!./source/blocks/tooltip-trigger/style.css
    Module build failed: Error: Cannot find module '0'
        at Function.Module._resolveFilename (module.js:440:15)
        at Function.Module._load (module.js:388:25)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at load (/code/webpack2/ss2/node_modules/postcss-load-plugins/lib/loadPlugins.js:21:50)
        at /code/webpack2/ss2/node_modules/postcss-load-plugins/lib/loadPlugins.js:27:18
        at Array.forEach (native)
        at loadPlugins (/code/webpack2/ss2/node_modules/postcss-load-plugins/lib/loadPlugins.js:26:24)
        at /code/webpack2/ss2/node_modules/postcss-load-config/index.js:19:18
```

**Comment by lavezzi1** [comment]
What is module '0'

**Comment by ai** [comment]
cc @michael-ciniawsky

**Comment by ai** [comment]
@lavezzi1 try this `postcss.config.js`:

```js
module.exports = {
    plugins: [
        'postcss-import': false,
        'postcss-nested': false,

        'postcss-simple-vars': false,
        'postcss-cssnext': {
            warnForDuplicates: false
        }),
        'postcss-calc': false,
        'postcss-functions': {
            functions: {
                darken: function (value, frac) {
                  var hsla = color(value).toHslaArray();
                  hsla[2] = Math.round(Math.max(Math.min(100, hsla[2] - hsla[2] * frac), 0));
                  return color().fromHsla(hsla).toHexString();
                }
            }
        }),
        'lost': false
    ]
}
```

**Comment by lavezzi1** [comment]
Additional errors:
```
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader!./~/postcss-loader!./~/vue-loader/lib/style-rewriter.js!./source/blocks/logo-spinner/style.css
    Module build failed: TypeError: Cannot read property 'config' of undefined
        at /code/webpack2/ss2/node_modules/postcss-load-config/index.js:19:36
```

**Comment by ai** [comment]
Oops, I forget to remove `)`:

Corrected config:

```
module.exports = {
    plugins: [
        'postcss-import': false,
        'postcss-nested': false,

        'postcss-simple-vars': false,
        'postcss-cssnext': {
            warnForDuplicates: false
        },
        'postcss-calc': false,
        'postcss-functions': {
            functions: {
                darken: function (value, frac) {
                  var hsla = color(value).toHslaArray();
                  hsla[2] = Math.round(Math.max(Math.min(100, hsla[2] - hsla[2] * frac), 0));
                  return color().fromHsla(hsla).toHexString();
                }
            }
        },
        'lost': false
    ]
}
```

**Comment by lavezzi1** [comment]
@ai nothing changes. The same errors.

**Comment by ai** [comment]
@lavezzi1 try this one (I forget to change `[]` to `{}`):

```js
module.exports = {
    plugins: {
        'postcss-import': false,
        'postcss-nested': false,

        'postcss-simple-vars': false,
        'postcss-cssnext': {
            warnForDuplicates: false
        },
        'postcss-calc': false,
        'postcss-functions': {
            functions: {
                darken: function (value, frac) {
                  var hsla = color(value).toHslaArray();
                  hsla[2] = Math.round(Math.max(Math.min(100, hsla[2] - hsla[2] * frac), 0));
                  return color().fromHsla(hsla).toHexString();
                }
            }
        },
        'lost': false
    }
}
```

**Comment by lavezzi1** [comment]
@ai Black magician! Works! Big thanks.

**Comment by ai** [comment]
:) I fixed example in docs.

Could you help in second test. Could you set PostCSS plugins in webpack config instead of PostCSS config?

Replace `'postcss-loader'` to:

```
{
  loader: 'postcss-loader',
  options: {
    plugins: () => {		
      return [		
          require('postcss-import')({		
              addDependencyTo: webpack		
          }),		
          require('postcss-nested')(),		
          require('postcss-simple-vars'),		
          require('postcss-cssnext')({		
              warnForDuplicates: false		
          }),		
          require('postcss-calc'),		
          require('postcss-functions')({		
              functions: {		
                  darken: function (value, frac) {		
                    var hsla = color(value).toHslaArray();		
                    hsla[2] = Math.round(Math.max(Math.min(100, hsla[2] - hsla[2] * frac), 0));		
                    return color().fromHsla(hsla).toHexString();		
                  }		
              }		
          }),		
          require('lost')		
      ]
    }
  }
}
```

And remove `postcss.config.js`

**Comment by michael-ciniawsky** [comment]
@lavezzi1 so ```postcss.config.js```worked for you?  if you haven't already update to ```webpack v2.1.0-beta.25``` it has lots of updates

@ai  i'm on it testing the webpack, i'm aware of the issues :). sokra replied and for webpack 2 `options` must be an object or string but can contain a funtion inside


```js
{
  loader: 'postcss-loader',
  options: { // -> {Object}
    plugins: () => { // -> {Function}        
      return [      
          require('postcss-import')({ addDependencyTo: webpack })  
          // addDependencyTo is deprecated 
      ]
    }
  }
}
```

my question is, how the options will/should look like when e.g parser needs to be set etc?

```js
{
  loader: 'postcss-loader',
  options: { // -> {Object}
    postcss: () => { // -> {Function}  e.g options[config] ? postcss : config      
      return {
        parser: 'sugarss',
        plugins: [
          require('postcss-import')()  
        ]
      }
    }
  }
}
```

**Comment by ai** [comment]
@michael-ciniawsky we fixed this issue 😊👍 it was my mistake, I used wrong config example docs (array instead of object).

I think we don't need dynamic parser, so we could set function only to plugins.

**Comment by michael-ciniawsky** [comment]
> I think we don't need dynamic parser, so we could set function only to plugins.

kk, but how will the config look like if you want to set parser, syntay, stringifier in loader.options

```js
{
  loader: 'postcss-loader',
  options: { 
    parser: 'sugarss',
    plugins: (ctx)  => { 
      return [
        require('postcss-import')({ addDependencyTo: ctx.addDependencyTo })  
        // ctx.addDependencyTo for e.g but obsolete  ctx === var loader = this
      ]
    }
  }
}
```
?

**Comment by ai** [comment]
@michael-ciniawsky you could ignore `addDependencyTo` case, we found better solution

**Comment by michael-ciniawsky** [comment]
@ai yep i have seen it in the source very nice :), this was a stupid example of passing the loader context, besides that is the example above correct?

**Comment by ai** [comment]
Yeap, it is how I see it.
