### ISSUE TITLE
Can't build when uses extract-text-webpack-plugin

### ISSUE THREAD

**Issue by abouthiroppy** [postcss/postcss-loader#132]
I used webpack@2.1.0-beta.25, extract-text-webpack-plugin@2.0.0-beta.4, and postcss-loader@1.1.0.

## webpack.config.js
```
{
  module: {
    rules: [{
      test  : /\.css$/,
      loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style',
        loader: [{
          loader: 'css',
          query: {
            modules       : true,
            localIdentName: '[path]___[name]__[local]___[hash:base64:5]'
          }
        }, {
          loader: 'postcss',
          query: {
            sourceMap: 'inline',
            plugins: [
              require('autoprefixer')(),
              require('postcss-cssnext')()
            ]
          }
        }]
      }),
    }]
  }
}
```

## output in postcss-loader
Checked `options`'s value [index.js#L9](https://github.com/postcss/postcss-loader/blob/master/index.js#L9)

```
[ null,
  { version: '5.2.5',
    plugins:
     [ null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null,
       null ],
    postcssPlugin: 'postcss-cssnext',
    postcssVersion: '5.2.5' } ]
```

## error
```

ERROR in ./~/css-loader?{"modules":true,"sourceMap":true,"localIdentName":"[path]___[name]__[local]___[hash:base64:5]"}!./~/postcss-loader?{"sourceMap":"inline","plugins":[null,{"version":"5.2.5","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"5.2.5"}]}!./client/team/src/style.css
Module build failed: TypeError: Cannot read property 'postcss' of null
    at Processor.normalize (/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss/lib/processor.js:136:12)
    at new Processor (/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss/lib/postcss.js:73:10)
    at /Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss-loader/index.js:108:16
 @ ./client/team/src/style.css 4:14-500 13:2-17:4 14:20-506
 @ ./client/team/src/index.js

ERROR in ./client/team/src/style.css
Module build failed: Error
    at /Users/hoge/fuga/knowledge/piyo/test/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/hoge/fuga/knowledge/piyo/test/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/hoge/fuga/knowledge/piyo/test/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/hoge/fuga/knowledge/piyo/test/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at /Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss-loader/index.js:127:13
    at process._tickCallback (internal/process/next_tick.js:103:7)

ERROR in /Users/hoge/fuga/knowledge/piyo/test/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/hoge/fuga/knowledge/piyo/test/node_modules/style-loader/index.js!/Users/hoge/fuga/knowledge/piyo/test/node_modules/css-loader/index.js?{"modules":true,"sourceMap":true,"localIdentName":"[path]___[name]__[local]___[hash:base64:5]"}!/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss-loader/index.js?{"sourceMap":"inline","plugins":[null,{"version":"5.2.5","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"5.2.5"}]}!/Users/hoge/fuga/knowledge/piyo/test/client/team/src/style.css doesn't export content
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader?{"modules":true,"sourceMap":true,"localIdentName":"[path]___[name]__[local]___[hash:base64:5]"}!./~/postcss-loader?{"sourceMap":"inline","plugins":[null,{"version":"5.2.5","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"5.2.5"}]}!./client/team/src/style.css
    Module build failed: TypeError: Cannot read property 'postcss' of null
        at Processor.normalize (/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss/lib/processor.js:136:12)
        at new Processor (/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss/lib/processor.js:51:25)
        at postcss (/Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss/lib/postcss.js:73:10)
        at /Users/hoge/fuga/knowledge/piyo/test/node_modules/postcss-loader/index.js:108:16
        at process._tickCallback (internal/process/next_tick.js:103:7)
```

Thanks.

**Comment by ai** [comment]
Use PostCSS common config as mentioned in docs.

**Comment by abouthiroppy** [comment]
Oops... I overlooked the config file in docs. Thanks.
