### ISSUE TITLE
Error: Can't resolve url in font face

### ISSUE THREAD

**Issue by craigcosmo** [postcss/postcss-loader#173]
stackstrace
```
ERROR in ./app/style/globalStyle/font.css
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './font/MuseoSansRounded-100.woff2' in '/Users/craigcosmo/Dropbox/Code/thatilike front/app/style/globalStyle'
    at factoryCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/Compilation.js:259:39)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:3694:9
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:934:13)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:840:16
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:3691:13
    at apply (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:21:25)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:56:12
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onResolved (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
 @ ./app/component/Page.js 22:0-40
 @ ./app/redux/MainContainer.js
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1111 ./app/index.js

ERROR in ./app/style/globalStyle/font.css
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './font/MuseoSansRounded-100.woff2' in '/Users/craigcosmo/Dropbox/Code/thatilike front/app/style/globalStyle'
    at factoryCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/Compilation.js:259:39)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:3694:9
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:934:13)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:840:16
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:3691:13
    at apply (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:21:25)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/async/dist/async.js:56:12
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onResolved (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)

ERROR in /Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/extract-text-webpack-plugin/loader.js??ref--4-0!/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/style-loader/index.js!/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/css-loader/index.js?sourceMap&importLoaders=1!/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/postcss-loader/index.js?sourceMap&parser=postcss-scss!/Users/craigcosmo/Dropbox/Code/thatilike front/app/style/globalStyle/font.css doesn't export content
```

post.config.js
```js
module.exports = {
	plugins: {
		'postcss-discard-comments': {comments:{removeAll: true}},
		'precss':{},
		'postcss-cssnext': {
			browsers: ['last 2 versions', '> 5%'],
			features: {autoprefixer:false}
		},
	},
}
```

webpack.config.js

```
{
	module: {
		rules: [
			{
				test: /\.(css)$/,
				loader: ExtractTextPlugin.extract({
					fallbackLoader: 'style-loader',
					loader: [
						{ loader: 'css-loader?sourceMap&importLoaders=1'},
						{ loader: 'postcss-loader?sourceMap&parser=postcss-scss'},
					]
				})
			},
		]
	},
	resolve: {
		modules: ['app', 'app/image', 'app/font', 'node_modules']
	},
}
```

font.css
```css
@font-face {
  font-family: 'msu';
  font-style: normal;
  font-weight: 100;
  src: local('msu light'), url(font/MuseoSansRounded-100.woff2) format('woff2');
}
```

home.scss
```js
.div{ background: url('image/bg.png')}
```

**Comment by ai** [comment]
Will you have a error if you will remove postcss-loader?

**Comment by craigcosmo** [comment]
If I remove `postcss-loader` I will have no error.

**Comment by ai** [comment]
And if you will remove extract text plugin?

**Comment by craigcosmo** [comment]
If I remove `extract text plugin` I will have no error as well.

**Comment by craigcosmo** [comment]
I made demo here https://github.com/craigcosmo/base-webpack-2-demo

**Comment by ai** [comment]
You should write to extract-text-plugin. I could not see how it should be relevant with postcss-loader.

@michael-ciniawsky do you agree? I think you saw some issue like it before.

**Comment by craigcosmo** [comment]
I figure out, I misconfig webpack. Webpack css loader doesn't by default resolve asset. 

The reason I can do  `.div{ background: url('image/bg.png')}` is because that `.div` is declared in side a `.scss`  file. For `scss` I was using babel-plugin-react-css-module which actually helps resolve asset.
