### ISSUE TITLE
Error: Cannot find module 'autoprefixier'

### ISSUE THREAD

**Issue by towry** [postcss/postcss-loader#187]
// packages info
```
webpack@2.2.1
autoprefixer@6.7.7
postcss-loader@1.3.3
```

Why the `postcss-loader` can not find the `autoprefixer` package?

// webpack config 
```js
// loaders
 { test: /\.scss$/, include: /(app\/styles|src\/lib)/, loader: cssExtractTextPlugin.extract({
	fallback: 'style-loader',
	use: 'css-loader?sourceMap!postcss-loader!sass-loader?outputStyle=expanded&sourceMap'
}) },

{ test: /\.scss$/, exclude: /(app\/styles|src\/lib)/, loader: cssExtractTextPlugin.extract({
	fallback: 'style-loader',
	use: [
		{ loader: 'css-loader', options: { modules: true, camelCase: true, importLoaders: 2, sourceMap: true, localIdentName: '[local]___[hash:base64:5]' } },
		{ loader: 'postcss-loader' },
		{ loader: 'sass-loader', options: { outputStyle: 'expanded', sourceMap: true} }
	],
}) },

// ...
        resolve: {
		modules: [
			'node_modules',
			'src',
		],
		extensions: ['.json', '.js'],
		alias: {
			vue: 'vue/dist/vue.js'
		}
	},
/ ...
```

// postcss.config.js

```js

console.log('----------------------');

var autoprefixier = require('autoprefixier');

console.log('===================')

module.exports = {
	plugins: [
		autoprefixier({ browsers: 'last 10 version' }),
	]
}
```

```
// outputs
----------------------
----------------------
----------------------
----------------------
----------------------
----------------------
----------------------
----------------------
----------------------
----------------------
./~/css-loader?{"modules":true,"camelCase":true,"importLoaders":2,"sourceMap":true,"localIdentName":"[local]___[hash:base64:5]"}!./~/postcss-loader!./~/sass-loader?{"outputStyle":"expanded","sourceMap":true}!./src/app/ui/Message/Message.scss
Module build failed: Error: Cannot find module 'autoprefixier'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function._module2.default._resolveFilename (/Users/towry/Projects/abc/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/towry/Projects/abc/postcss.config.js:5:21)
    at Module._compile (module.js:570:32)
    at requireFromString (/Users/towry/Projects/abc/node_modules/require-from-string/index.js:27:4)
    at /Users/towry/Projects/abc/node_modules/cosmiconfig/lib/loadJs.js:11:15
 @ ./src/app/ui/Message/Message.scss 4:14-201 13:2-17:4 14:20-207
```

**Comment by towry** [comment]
I fixed this by not use a `postcss.config.js` in my project root directory, I put the plugins options in the webpack config files.

**Comment by michael-ciniawsky** [comment]
@towry 

```diff
- var autoprefixier = require('autoprefixier');
+ var autoprefixer = require('autoprefixer');
```

`autoprefixier => autoprefixer` 😛

**Comment by michael-ciniawsky** [comment]
Please ensur it is installed correctly and the package name in `package.json` is also correct in case a package named `autoprefixier` exists run `npm prune && npm i -D autoprefixer` after fixing  `package.json`

**Comment by littp** [comment]
@michael-ciniawsky 答案修复成功，谢谢！

**Comment by rmar72** [comment]
near 2019 update, following a webpack tutorial that uses postcss.config.js the autopprefixer is required, but got an error for missing module, the above worked ^ npm prune && npm i -D autoprefixer thanks michael-ciniawsky

**Comment by MiguelMendozaMolina** [comment]
hello everyone I confirm that this solution worked for me with the error problem - ./components/Loader/Loader.style.js Error: [styled-jsx-plugin-postcss] postcss failed with Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer' thanks @michael-ciniawsky
