### ISSUE TITLE
[2.0.2] Don't fail on `sourceMap: false` && previous map (options.sourceMap)

### ISSUE THREAD

**Issue by doberkofler** [postcss/postcss-loader#217]
After upgrading to postcss-loader 2.0.2 I received the following type of error message for almost all files:
```
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot create property 'prev' on boolean 'false'
    at Promise.resolve.then.then (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\postcss-loader\lib\index.js:131:47)
    at runLoaders (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\webpack\lib\NormalModule.js:192:19)
    at D:\MyDev\ljs_app\trunk\periscope\build\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at D:\MyDev\ljs_app\trunk\periscope\build\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\postcss-loader\lib\index.js:172:71)
```

**Comment by michael-ciniawsky** [comment]
Did you set { sourceMap: true } in `postcss-loader` when using source maps? It fails because `postcss-loader` doesn't generate a source map by default anymore and dicardes the previous source map, albeit the hard fail is a bug 😛

**Comment by doberkofler** [comment]
@michael-ciniawsky Thank you. It's working now.

**Comment by michael-ciniawsky** [comment]
Fixed by https://github.com/postcss/postcss-loader/commit/159b66a
Released in [v2.0.3](https://github.com/postcss/postcss-loader/releases/tag/v2.0.3)

**Comment by duleigiser** [comment]
I  use **ExtractTextPlugin** to put all kinds of style files into one files.
> here is my config files fragments
```
{
        test: /\.(css$|styl)$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use://"css-loader!postcss-loader!stylus-loader"
           [
             "css-loader",
           {
              loader:"postcss-loader",
              options: {
               sourceMap:true //webpack config when we set `dev-tool: true'
             }
            },
            {
              loader:"stylus-loader",//put this loader  in the end
              options: {
                importLoaders: 1
              }
            }
          ]
        })
      }

```

**Comment by TrejGun** [comment]
@michael-ciniawsky 
hi there!
i can see fix in repo but when i'm installing from npm i see old code
```
    if (sourceMap && typeof map === 'string') map = JSON.parse(map)
    if (sourceMap && map) options.map.prev = map
```
you can see in zip package here
https://github.com/postcss/postcss-loader/releases/tag/v2.0.6

**Comment by michael-ciniawsky** [comment]
How do you consume `postcss-loader`? npm? 

[**`index.js`**](https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L139-L140) (Current `master`)
```js
if (sourceMap && typeof map === 'string') map = JSON.parse(map)
if (sourceMap && map) options.map.prev = map
```

What is the issue ? 😛

**Comment by TrejGun** [comment]
@michael-ciniawsky oops

yes i'm consuming it via npm
and i have this error

```
ERROR in ./client/shared/components/imageViewer.less
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot create property 'prev' on boolean 'true'
at Promise.resolve.then.then (~/node_modules/postcss-loader/lib/index.js:135:44)
at <anonymous>
at runLoaders (~/node_modules/webpack/lib/NormalModule.js:194:19)
at ~/node_modules/loader-runner/lib/LoaderRunner.js:364:11
at ~/node_modules/loader-runner/lib/LoaderRunner.js:230:18
at context.callback (~/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at Promise.resolve.then.then.catch (~/node_modules/postcss-loader/lib/index.js:176:71)
at <anonymous>
@ ./client/shared/components/imageViewer.jsx 17:0-28
@ ./client/office/components/vehicle/read.jsx
@ ./client/office/components/vehicle/index.jsx
@ ./client/office/app.jsx
@ ./client/office.js
@ multi react-hot-loader/patch webpack-hot-middleware/client?path=http://localhost:5000/__webpack_hmr ./client/office
```

my config is here https://github.com/postcss/postcss-loader/issues/283
