### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by obartra** [postcss/postcss-loader#231]
When migrating from `1.3.3` to `2.0.0` I get the following error (Node 7.9.0):

```bash
Node#before is deprecated. Use Node#raws.before
(node:50262) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'parent' of undefined
(node:50262) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:50262) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot set property 'parent' of undefined
```
Which is a particularly useless message from Node. If I run instead: `node --trace-warnings node_modules/.bin/webpack --config webpack.config.js` I get:

```
(node:50319) TypeError: Cannot set property 'parent' of undefined
    at Root.removeChild ([project]/node_modules/postcss/lib/container.es6:442:9)
    at Root.removeChild ([project]/node_modules/postcss/lib/root.es6:29:16)
    at [project]/node_modules/postcss-loader/node_modules/postcss/lib/container.es6:611:38
    at Array.map (native)
    at Root.normalize ([project]/node_modules/postcss-loader/node_modules/postcss/lib/container.es6:608:31)
    at Root.normalize ([project]/node_modules/postcss-loader/node_modules/postcss/lib/root.es6:32:21)
    at Root.insertBefore ([project]/node_modules/postcss-loader/node_modules/postcss/lib/container.es6:375:26)
    at AtRule.replaceWith ([project]/node_modules/postcss-loader/node_modules/postcss/lib/node.es6:232:29)
    at [project]/node_modules/postcss-partial-import/index.js:109:21
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
Node#moveAfter was deprecated. Use Node#after.
```

This persists on the latest version (`2.0.5`) of postcss-loader.

**Comment by michael-ciniawsky** [comment]
`postcss-loader` uses PostCSS v6 and this is an PostCSS API error from one of your plugins (`postcss-partial-import`)

>  at [project]/node_modules/postcss-partial-import/index.js:109:21

Open an issue at `postcss-partial-import` please 😛

**Comment by obartra** [comment]
Sure thing I filed it https://github.com/jonathantneal/postcss-partial-import/issues/40. The issue remains though with postcss-loader being compatible with it on version 1.3.3 and not on 2.0.0 onwards

**Comment by michael-ciniawsky** [comment]
Yep, but I can't do anything in `postcss-loader` scope to address this :D, the author is aware of it already via PostCSS Gitter it's breaing is gulp setup aswell...

**Comment by obartra** [comment]
Ah got it, thanks for checking!
