### ISSUE TITLE
Webpack 2: postcss-loader doesn't work in conjunction with less-loader

### ISSUE THREAD

**Issue by bfday** [postcss/postcss-loader#240]
Maybe i am doing somthing wrong (it is strongly possible).
I have read every possible source of information and didn't find answer. (i think it is before my nose but i can't see it)
I would to process my .less files using less-loader and then by postcss-loader to add vendor prefixes.

but when i add postcss-loader into config like this

```
...
{
                test: /(\.less|\.css$)$/,
                exclude: /(node_modules)/,
                use: ExtractTextPlugin.extract({
                    // use style-loader in development
                    fallback: 'style-loader',
                    use: 'css-loader!postcss-loader!less-loader' // right here in the middle (without !postcss-loader it works fine)
                })
            },
...
```
it starts to porduce errors
[https://cloud.mail.ru/public/7NWG/B5Uo6fD6U](url)
and the final part [https://s.mail.ru/LvCH/qEVZ7bUvJ](url)

Errors text copy:
```
ERROR in /var/www/bp/~/css-loader!/var/www/bp/~/postcss-loader!/var/www/bp/~/less-loader/dist!../css/main.less
Module build failed: Unnecessary curly bracket (1:4)

> 1 | h1 {
    |    ^
  2 |   display: flex;
  3 | }

 @ ../css/main.less 4:14-174
 @ ./styles.js

ERROR in ../css/main.less
Module build failed: ModuleBuildError: Module build failed: Unnecessary curly bracket (1:4)

> 1 | h1 {
    |    ^
  2 |   display: flex;
  3 | }

    at runLoaders (/var/www/bp/node_modules/webpack/lib/NormalModule.js:192:19)
    at /var/www/bp/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/bp/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/bp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/bp/node_modules/postcss-loader/index.js:146:13

ERROR in /var/www/bp/node_modules/extract-text-webpack-plugin/loader.js??ref--1-0!/var/www/bp/node_modules/style-loader/index.js!/var/www/bp/node_modules/css-loader/index.js!/var/www/bp/node_modules/postcss-loader/index.js!/var/www/bp/node_modules/less-loader/dist/index.js!/var/www/bp/app/Resources/css/main.less doesn't export content
Child extract-text-webpack-plugin:
       [0] /var/www/bp/~/css-raw-loader/css-base.js 1.6 kB {0} [built]
       [1] /var/www/bp/~/css-raw-loader?-minimize!/var/www/bp/~/sass-loader/lib/loader.js!../css/main.scss 467 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] /var/www/bp/~/css-raw-loader/css-base.js 1.6 kB {0} [built]
       [1] /var/www/bp/~/css-raw-loader?-minimize!/var/www/bp/~/sass-loader/lib/loader.js!../css/main.sass 467 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] /var/www/bp/~/css-loader!/var/www/bp/~/postcss-loader!/var/www/bp/~/less-loader/dist!../css/main.less 371 bytes {0} [built] [failed] [1 error]

    ERROR in /var/www/bp/~/css-loader!/var/www/bp/~/postcss-loader!/var/www/bp/~/less-loader/dist!../css/main.less
    Module build failed: Unnecessary curly bracket (1:4)

    > 1 | h1 {
        |    ^
      2 |   display: flex;
      3 | }

```

My
webpack.config.js
```
let
    webpack = require('webpack')
    , path = require('path')
    , i18nPlugin = require("i18n-webpack-plugin")

    , ExtractTextPlugin = require('extract-text-webpack-plugin')
    , autoprefixer = require('autoprefixer')
    , csswring = require('csswring')
    , CopyPlugin = require('copy-webpack-plugin')
    , node_modules_dir = path.join(__dirname, 'node_modules')
    , postcss = require('postcss')
    , precss = require('precss')
    , SplitByPathPlugin = require('webpack-split-by-path')
;

// let languages = {
//     "ru": require("./app/Resources/js/reactApp/i18n/ru.json"),
//     //"en": require("./app/Resources/js/reactApp/i18n/en.json")
// };

const extractProcessedCss = new ExtractTextPlugin({
    filename: "[name].css"
});

let
    projectRootPathRelative = './app/Resources'
    , projectEntryPathRelative = projectRootPathRelative + '/js'
    , assetsPathRelative = 'web/dist'
    , projectRootPath = path.join(__dirname, projectRootPathRelative)      //path to root
    , projectEntryPath = path.join(__dirname, projectEntryPathRelative) //path to input dir
    , assetsPath = path.join(__dirname, assetsPathRelative) //path to output dir
;

let config = {
    devtool: 'eval',
    context: path.join(__dirname, projectEntryPathRelative),
    entry: {
        react: './reactApp'
        , bundle: './index.js'
        , styles: './styles.js'
    },
    output: {
        path: path.join(__dirname, assetsPathRelative),
        filename: '[name].js',
        chunkFilename: "[name].[id].js",
        publicPath: './'
    },
    plugins: [
        extractProcessedCss,
        autoprefixer,
        new SplitByPathPlugin([
            {
                name: 'vendor',
                path: path.join(__dirname, 'node_modules')
            }
        ], {
            manifest: 'app-entry'
        })
        //,new webpack.OldWatchingPlugin()
        //,new i18nPlugin(languages['ru'])
    ],
    // resolve: { // which extensions should be resolved
    //     extensions: ['', '.js', '']
    // },
    module: {
        rules: [
            {
                test: /\.js?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                options: {
                    presets: ["es2015", "stage-0", "react"]
                    , plugins: ["transform-decorators-legacy"]
                }
                // include: path.join(__dirname, 'src')
            },
            {
                test: /(\.less|\.css$)$/,
                exclude: /(node_modules)/,
                use: ExtractTextPlugin.extract({
                    // use style-loader in development
                    fallback: 'style-loader',
                    use: 'css-loader!postcss-loader!less-loader'
                })
            },
            {
                test: /(\.sass|\.scss)$/,
                exclude: /(node_modules)/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-raw-loader?-minimize!sass-loader'
                })
            },
            {
                test: /\.(png|jpg|gif)$/,
                exclude: /(node_modules)/,
                use: 'url-loader?prefix=img/&limit=10&q=100&name=[name].[ext]'
            },
            {
                test: /\.svg$/,
                exclude: /(\.font\.|\/sprite\/)/,
                use: 'url?limit=10&mimetype=image/svg+xml&prefix=font&name=[name].[ext]'
            },
            {
                test: /\/sprite\//,
                use: 'svg-sprite?' + JSON.stringify({
                    name: 'spr-[name]',
                    prefixize: true,
                    exclude: /(\.font\.)/,
                })
            },
            {
                test: /\.woff$/,
                use: 'url-loader?prefix=font/&limit=0&mimetype=application/font-woff&name=[name].[ext]'
            },
            {
                test: /\.woff2$/,
                use: 'url-loader?prefix=font/&limit=0&mimetype=application/font-woff2&name=[name].[ext]'
            }, {
                test: /\.eot$/,
                use: 'file?prefix=font/&name=[name].[ext]'
            },
            {
                test: /\.(ttf|otf)$/,
                use: 'url?limit=0&mimetype=application/octet-stream&prefix=font/&name=[name].[ext]'
            },
            {
                test: /\.font\.(js|json)$/,
                exclude: /(node_modules)/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-raw-loader!postcss-cssnext-loader?package=defaults!less-loader!fontgen-loader'
                })
            }
        ]
    }
};

module.exports = config;
```

Also i have
 postcss.config.js
```
var
    autoprefixer = require('autoprefixer')
;
module.exports = {
    parser: 'sugarss',
    plugins: {
        autoprefixer
    }
};
```

package.json

```
{
  "name": "bp",
  "version": "1.0.0",
  "description": "bp ==",
  "main": "webpack.config.js",
  "directories": {
    "test": "tests"
  },
  "dependencies": {
    "autoprefixer-core": "^6.0.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-raw-loader": "^0.1.1",
    "cssnext": "^1.8.4",
    "csswring": "^6.0.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "html-webpack-plugin": "^2.28.0",
    "i18n-webpack-plugin": "^0.3.0",
    "mobx": "^3.1.9",
    "mobx-react": "^4.1.8",
    "postcss-cssnext": "^2.11.0",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^1.3.3",
    "precss": "^1.4.0",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "scss-loader": "0.0.1",
    "sugarss": "^1.0.0",
    "webpack": "^2.5.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-split-by-path": "^2.0.0"
  },
  "repository": "git@git.gibdev.ru:bp",
  "keywords": [],
  "author": "stepanov <stepanov@stepanov.gibdev.ru>",
  "license": "ISC",
  "scripts": {
    "build": "webpack"
  },
  "devDependencies": {
    "assets-webpack-plugin": "^3.5.1",
    "autoprefixer": "^6.7.6",
    "babel-core": "^6.23.1",
    "babel-preset-env": "^1.2.1",
    "css-loader": "^0.26.4",
    "extract-file-loader": "^0.1.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.1",
    "image-webpack-loader": "^3.2.0",
    "less": "^2.7.2",
    "less-loader": "^4.0.0",
    "node-sass": "^4.5.0",
    "postcss-loader": "^1.3.3",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.13.2",
    "webpack": "^2.5.1",
    "webpack-dashboard": "^0.3.0",
    "webpack-init": "^0.1.2"
  }
}
```

**Comment by bfday** [comment]
package.json

```
{
  "name": "bp",
  "version": "1.0.0",
  "description": "bp ==",
  "main": "webpack.config.js",
  "directories": {
    "test": "tests"
  },
  "dependencies": {
    "autoprefixer-core": "^6.0.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-raw-loader": "^0.1.1",
    "cssnext": "^1.8.4",
    "csswring": "^6.0.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "html-webpack-plugin": "^2.28.0",
    "i18n-webpack-plugin": "^0.3.0",
    "mobx": "^3.1.9",
    "mobx-react": "^4.1.8",
    "postcss-cssnext": "^2.11.0",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^1.3.3",
    "precss": "^1.4.0",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "scss-loader": "0.0.1",
    "sugarss": "^1.0.0",
    "webpack": "^2.5.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-split-by-path": "^2.0.0"
  },
  "repository": "git@git.gibdev.ru:bp",
  "keywords": [],
  "author": "stepanov <stepanov@stepanov.gibdev.ru>",
  "license": "ISC",
  "scripts": {
    "build": "webpack"
  },
  "devDependencies": {
    "assets-webpack-plugin": "^3.5.1",
    "autoprefixer": "^6.7.6",
    "babel-core": "^6.23.1",
    "babel-preset-env": "^1.2.1",
    "css-loader": "^0.26.4",
    "extract-file-loader": "^0.1.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.1",
    "image-webpack-loader": "^3.2.0",
    "less": "^2.7.2",
    "less-loader": "^4.0.0",
    "node-sass": "^4.5.0",
    "postcss-loader": "^1.3.3",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.13.2",
    "webpack": "^2.5.1",
    "webpack-dashboard": "^0.3.0",
    "webpack-init": "^0.1.2"
  }
}

```

**Comment by michael-ciniawsky** [comment]
` parser: 'sugarss'` , if you have `.css` files using SugarSS syntax but your `.less` files get compiled to **standard** CSS (with curley brackets), you need a dynamic config to handle that.

```js
module.exports = ({ file, options, env }) => ({
   parser: file.extname === '.css' ? 'sugarss' : false 
   // .css (SugarSS) => use sugarss parser (SugarSS Parser)
   // .(less|sass) (CSS) => use css parser (PostCSS Parser)
   plugins: {...}
})
```

⚠️  This requires `postcss-loader >= v2.0.0`, otherwise the syntax is 

```diff
- file.extname === '.css' ? 'sugarss' : false 
+ ctx.webpack.resourcePath.endsWith('.css') ? 'sugarss' : false
```

**Comment by michael-ciniawsky** [comment]
`css-raw-loader` can be replaced by `postcss-loader >= v2.0.0` aswell, since it will export a 'raw' JS Module, if it is the last loader in the chain

**Comment by michael-ciniawsky** [comment]
The `loader!loader!loader!` is deprecated, please use webpack 2 config syntax
