### ISSUE TITLE
[2.0.5] npm@5 issue

### ISSUE THREAD

**Issue by HeadFox** [postcss/postcss-loader#249]
Can't run webpack with npm5 :
 `
TypeError: parser.loop is not a function
    at scssParse (/Users/lucienpeslier/PackIt/node_modules/postcss-scss/lib/scss-parse.js:21:12)
    at new LazyResult (/Users/lucienpeslier/PackIt/node_modules/postcss/lib/lazy-result.js:66:24)
    at Processor.process (/Users/lucienpeslier/PackIt/node_modules/postcss/lib/processor.js:117:12)
    at getCode.then.code (/Users/lucienpeslier/PackIt/node_modules/stylelint/lib/getPostcssResult.js:83:29)
`

**Comment by michael-ciniawsky** [comment]
Please post your `package.json && webpack.config.js && postcss.config.js` I don't believe this is an npm issue :), but `npm@5`got a enterily new cache implementation, so maybe run`npm cache clean --force` and in your project `rm -rf node_modules && npm i`

**Comment by HeadFox** [comment]
Hey ! 
So i tried what you ask me to do, but after npm install with npm5 i still got the error and when i install with yarn for example, webpack command perfectly work.

You can check the 3 files here : https://github.com/HeadFox/PackIt

**Comment by michael-ciniawsky** [comment]
@HeadFox Do you still have this regression? I couldn't reproduce your issue

**Comment by evilebottnawi** [comment]
@HeadFox don't use `npm@5` right now in production, now it is very buggy, give time to new npm become more stable

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions :)
