### ISSUE TITLE
Upgrade to ^2.0.5 broke relative imports

### ISSUE THREAD

**Issue by damianobarbati** [postcss/postcss-loader#251]
Just upgraded from 1.x.x to 2.0.5 and now relative imports in css url() are broken, no assets can be found: is this expected? 

Repro here => https://github.com/damianobarbati/react-simple-app
Just yarn install, yarn build:dev and fonts are not found.

```
//loaders for extract-css
const extractCssLoaders = [{
    loader: 'css-loader',
    options: {
        modules: true,
        localIdentName: cssScopedName,
        importLoaders: 1,
        minimize: true,
    },
},{
    loader: 'resolve-url-loader',
},{
    loader: 'postcss-loader',
    options: {
        plugins: [
            cssnano({
                reduceIdents: false,
                discardDuplicates: true,
                autoprefixer: false,
                zindex: false,
            }),
            autoprefixer({
                remove: false
            }),
        ],
    },
},{
    loader: 'sass-loader',
}];

//later in rules
        },{
            test: [/\.css$/i, /\.scss$/i, /\.sass$/i],
            loader: ExtractTextPlugin.extract({ use: extractCssLoaders, fallback: 'style-loader' }),
        },{
```

**Comment by michael-ciniawsky** [comment]
Could you try without `resolve-url-loader` && `css-loader` minimize uses `cssnano`, you won't need it as a plugin in `postcss-loader`

**Comment by damianobarbati** [comment]
@michael-ciniawsky thanks for helping! Same error without resolve-url-loader :(((

**Comment by michael-ciniawsky** [comment]
Can you post some output please ?

**Comment by damianobarbati** [comment]
Sure:

```
Counting objects: 21, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (21/21), 185.43 KiB | 0 bytes/s, done.
Total 21 (delta 3), reused 2 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:damianobarbati/react-simple-app.git
   6ec4558..28f62d3  master -> master
macbook:react-simple-app damiano$ yarn build:dev
yarn build:dev v0.24.5
$ NODE_ENV=development yarn webpack -- --config ./config/webpack.config.js --watch --progress 
yarn webpack v0.24.5
$ ./node_modules/webpack/bin/webpack.js --config ./config/webpack.config.js --watch --progress
clean-webpack-plugin: /Users/damiano/Desktop/react-simple-app/build has been removed.
 10% building modules 1/1 modules 0 active                                         
Webpack is watching the files…

 10% building modules 7/37 modules 30 active ...-app/node_modules/redux/es/compose.jsbabel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": "58"
}

Modules transform: false

Using plugins:

Using polyfills:
  web.timers {"chrome":"58"}
  web.immediate {"chrome":"58"}
  web.dom.iterable {"chrome":"58"}
Hash: 887a02f091ee8e9877f8                                                              
Version: webpack 2.6.1
Time: 8930ms
[./app/index.js] ./app/index.js 575 bytes {1} [built]
[./app/index.scss] ./app/index.scss 3.94 kB {1} [built] [failed] [1 error]
[./app/reducers.js] ./app/reducers.js 0 bytes {1} [built]
[./app/router.js] ./app/router.js 821 bytes {1} [built]
[./node_modules/react-create-app/dist/index.min.js] ./~/react-create-app/dist/index.min.js 14.2 kB {1} [built]
[./node_modules/react-create-store/dist/index.min.js] ./~/react-create-store/dist/index.min.js 30.6 kB {1} [built]
[./node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {0} [built]
[./node_modules/react-redux/es/index.js] ./~/react-redux/es/index.js 230 bytes {0} [built]
[./node_modules/react-router-dom/es/index.js] ./~/react-router-dom/es/index.js 925 bytes {0} [built]
[./node_modules/react-router/es/index.js] ./~/react-router/es/index.js 637 bytes {0} [built]
[./node_modules/react-router/es/withRouter.js] ./~/react-router/es/withRouter.js 1.4 kB {0} [built]
[./node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
[./node_modules/redux/es/compose.js] ./~/redux/es/compose.js 965 bytes {0} [built]
[./node_modules/redux/es/index.js] ./~/redux/es/index.js 1.08 kB {0} [built]
   [0] multi react react-dom react-router react-router-dom redux react-redux 88 bytes {0} [built]
    + 263 hidden modules

ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
Module not found: Error: Can't resolve 'assets/sf.eot' in '/Users/damiano/Desktop/react-simple-app/app'
 @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:75-99 6:117-141
 @ ./app/index.scss
 @ ./app/index.js

ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
Module not found: Error: Can't resolve 'assets/sf.woff2' in '/Users/damiano/Desktop/react-simple-app/app'
 @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:192-218
 @ ./app/index.scss
 @ ./app/index.js

ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
Module not found: Error: Can't resolve 'assets/sf.woff' in '/Users/damiano/Desktop/react-simple-app/app'
 @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:250-275
 @ ./app/index.scss
 @ ./app/index.js

ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
Module not found: Error: Can't resolve 'assets/sf.ttf' in '/Users/damiano/Desktop/react-simple-app/app'
 @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:306-330
 @ ./app/index.scss
 @ ./app/index.js

ERROR in ./app/index.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve 'assets/sf.eot' in '/Users/damiano/Desktop/react-simple-app/app'
    at factoryCallback (/Users/damiano/Desktop/react-simple-app/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/Users/damiano/Desktop/react-simple-app/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/damiano/Desktop/react-simple-app/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel (/Users/damiano/Desktop/react-simple-app/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/damiano/Desktop/react-simple-app/node_modules/webpack/node_modules/async/dist/async.js:3838:9
    at /Users/damiano/Desktop/react-simple-app/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/damiano/Desktop/react-simple-app/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /Users/damiano/Desktop/react-simple-app/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /Users/damiano/Desktop/react-simple-app/node_modules/webpack/node_modules/async/dist/async.js:3835:13
    at resolvers.normal.resolve (/Users/damiano/Desktop/react-simple-app/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onResolved (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:283:15
    at resolver.doResolve.createInnerCallback (/Users/damiano/Desktop/react-simple-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)

ERROR in /Users/damiano/Desktop/react-simple-app/node_modules/extract-text-webpack-plugin/loader.js??ref--1-0!/Users/damiano/Desktop/react-simple-app/node_modules/style-loader/index.js!/Users/damiano/Desktop/react-simple-app/node_modules/css-loader/index.js??ref--1-2!/Users/damiano/Desktop/react-simple-app/node_modules/postcss-loader/lib/index.js??ref--1-3!/Users/damiano/Desktop/react-simple-app/node_modules/sass-loader/lib/loader.js!/Users/damiano/Desktop/react-simple-app/app/index.scss doesn't export content
Child html-webpack-plugin for "build/index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 965 bytes {0} [built]
    [./node_modules/lodash/lodash.js] ./~/lodash/lodash.js 540 kB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
Child html-webpack-plugin for "build/503.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/503.html] ./~/html-webpack-plugin/lib/loader.js!./app/503.html 395 bytes {0} [built]
    [./node_modules/lodash/lodash.js] ./~/lodash/lodash.js 540 kB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
Child extract-text-webpack-plugin:
    [./node_modules/css-loader/index.js?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./node_modules/postcss-loader/lib/index.js?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./node_modules/sass-loader/lib/loader.js!./app/index.scss] ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 583 bytes {0} [built]
    [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
    
    ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
    Module not found: Error: Can't resolve 'assets/sf.eot' in '/Users/damiano/Desktop/react-simple-app/app'
     @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:75-99 6:117-141
    
    ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
    Module not found: Error: Can't resolve 'assets/sf.woff2' in '/Users/damiano/Desktop/react-simple-app/app'
     @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:192-218
    
    ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
    Module not found: Error: Can't resolve 'assets/sf.woff' in '/Users/damiano/Desktop/react-simple-app/app'
     @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:250-275
    
    ERROR in ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss
    Module not found: Error: Can't resolve 'assets/sf.ttf' in '/Users/damiano/Desktop/react-simple-app/app'
     @ ./~/css-loader?{"modules":true,"localIdentName":"[name]__[local]--[chunkhash:base64:12]","importLoaders":1,"minimize":true}!./~/postcss-loader/lib?{"plugins":[{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"5.2.17"},null]}!./~/sass-loader/lib/loader.js!./app/index.scss 6:306-330
```

**Comment by damianobarbati** [comment]
Here the url requiring => https://github.com/damianobarbati/react-simple-app/blob/master/app/index.scss

**Comment by damianobarbati** [comment]
After loosing hours of life and mental health it turned out to be babel-css-modules plugin. 
Jesus, I'm sorry guys: closing this.

**Comment by damianobarbati** [comment]
Sorry to reopen this but I can confirm that upgrading from `"postcss-loader": "^1.3.3"` to `"postcss-loader": "^2.0.5"` is breaking relative imports.
Here repro before and after
Before and working =>
https://github.com/damianobarbati/react-simple-app/commit/984bc6a04b6db3d5d7566f2268042e66ae0bdfbe
After update and broken =>
https://github.com/damianobarbati/react-simple-app/commit/9c33d6714e542f81c824a659cba08f4938f7405a

Error thrown:
```
    ERROR in ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss
    Module not found: Error: Can't resolve '../logo.svg' in '/Users/damiano/Desktop/react-simple-app/app/styles'
     @ ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss 6:431-453
    
    ERROR in ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss
    Module not found: Error: Can't resolve './assets/sf.eot' in '/Users/damiano/Desktop/react-simple-app/app/styles'
     @ ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss 6:75-101 6:119-145
    
    ERROR in ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss
    Module not found: Error: Can't resolve './assets/sf.woff2' in '/Users/damiano/Desktop/react-simple-app/app/styles'
     @ ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss 6:196-224
    
    ERROR in ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss
    Module not found: Error: Can't resolve './assets/sf.woff' in '/Users/damiano/Desktop/react-simple-app/app/styles'
     @ ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss 6:256-283
    
    ERROR in ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss
    Module not found: Error: Can't resolve './assets/sf.ttf' in '/Users/damiano/Desktop/react-simple-app/app/styles'
     @ ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/common.scss 6:314-340
Child extract-text-webpack-plugin:
    [./node_modules/css-loader/index.js?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./node_modules/resolve-url-loader/index.js!./node_modules/postcss-loader/lib/index.js?{"plugins":[null]}!./node_modules/sass-loader/lib/loader.js!./app/styles/reset.scss] ./~/css-loader?{"modules":true,"camelCase":true,"localIdentName":"[name]-[local]","importLoaders":1,"minimize":{"reduceIdents":false,"discardDuplicates":true,"autoprefixer":false,"zindex":false}}!./~/resolve-url-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/reset.scss 980 bytes {0} [built]
    [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin:
    [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
        + 1 hidden modules
```

**Comment by michael-ciniawsky** [comment]
The before commit shows a major bump for `resolve-url-loader` :), which uses sourcemaps to resolve the urls, the paths for source maps (relative => absolute) changed in `postcss-loader`  >= v2.0.0, but why is `resolve-url-loader` needed ? :). You can try by commenting out [these lines](https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L149-L152) in `postcss-loader`  and if it works we can triage, if this change maybe reverted. Although I made this change because webpack seems to need absolute paths for source maps to work correctly according to it's author. Are you on a windows machine ?

**Comment by damianobarbati** [comment]
@michael-ciniawsky thanks so much for the effort!  
No I'm not on a windows machine but on MacOS.
I have no idea why the bump, I regularly upgrade dependencies to keep up to date.

I tried commenting out those lines but nothing (neither with relative-url-loader or not).

I'm using it so I can import assets with a relative url(./relative/path/to/current/file) in my scss files.

What other solutions do I have?

**Comment by michael-ciniawsky** [comment]
You paths are simly incorrect :)

```diff
@font-face {
    font-family: 'San Francisco';
-   src: url('./assets/sf.eot'); 
+   src: url('../assets/sf.eot'); 
-   src: url('./assets/sf.eot?#iefix') format('embedded-opentype'),
+   src: url('../assets/sf.eot?#iefix') format('embedded-opentype'),
-         url('../assets/sf.woff2') format('woff2'),
+         url('../assets/sf.woff2') format('woff2'),
-         url('./assets/sf.woff') format('woff'),
+        url('../assets/sf.woff') format('woff'),
-         url('./assets/sf.ttf') format('truetype');
+         url('../assets/sf.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
}

body {
-    background-image: url('../logo.svg');
+    background-image: url('../../logo.svg');
}

.fontSf {
    font-family: 'San Francisco';
}

.underline {
    text-decoration: underline;
}
```

Tested without `resolve-url-loader` && `build:dev`

**Comment by damianobarbati** [comment]
Oh my what a dumb. T-HA-N-K-S @michael-ciniawsky!
