### ISSUE TITLE
How to use postcss-js with Webpack? SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by mahnunchik** [postcss/postcss-loader#268]
I think issue https://github.com/postcss/postcss-js/issues/26 may be realted to `postcss-loader` not to `postcss-js` parser.

**Comment by mahnunchik** [comment]
### Copy of original issue https://github.com/postcss/postcss-js/issues/26

I've faced with the following error:

```bash
ERROR in ./src/test.style.js
Module build failed: /test-webpack/src/test.style.js:3
export default {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.exec (/test-webpack/node_modules/webpack/lib/NormalModule.js:127:12)
    at Promise.resolve.then.then (/test-webpack/node_modules/postcss-loader/lib/index.js:109:18)
    at <anonymous>
```

My `webpack.config.js`:

```js

const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.style.js$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 2 } },
          { loader: 'postcss-loader', options: { parser: 'postcss-js' } },
          'babel-loader'
        ]
      },
    ],
  },
};
```

`index.js`:

```js
import React from 'react';
import ReactDOM from 'react-dom';

import style from './test.style.js';

class Hello extends React.Component {
  render() {
    return <div style={style.main}>Hello World!</div>;
  }
}

ReactDOM.render(
  <Hello />,
  document.getElementById('root')
);
```

`test.style.js`:

```js
export default {
  'main': {
    color: 'black',
    height: 25,
    display: 'flex',
  }
}
```

#### Versions

```bash
$ node -v
v8.1.2
$ npm -v
5.0.3
```

```json
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.0",
    "babel-preset-env": "^1.5.2",
    "babel-preset-react-app": "^3.0.0",
    "css-loader": "^0.28.4",
    "postcss-js": "^1.0.0",
    "postcss-loader": "^2.0.6",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "style-loader": "^0.18.2",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.5.0",
```

**Comment by TrySound** [comment]
@mahnunchik The problem is that you are trying to run es-modules in node. postcss-js requires a value, not a string with code. `postcss-loader` checks if `postcss-js` is used and evaluate that code (runs in node). The result is passed to `postcss-js`. Use commonjs if you like this style.

**Comment by michael-ciniawsky** [comment]
@mahnunchik You need to add a babel plugin `transforms-add-module-exports` (something like that) and enure to have only one `export default` per `style.js`

**Comment by mahnunchik** [comment]
@TrySound using commonjs style module helps:

`test.style.js`:
```
module.exports = {
  'main': {
    color: 'black',
    height: 25,
    display: 'flex',
  }
}
```

@michael-ciniawsky if I add https://github.com/59naga/babel-plugin-add-module-exports and use es modules then it produces the same error: `SyntaxError: Unexpected token export`

My babel settings:

```json
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      "add-module-exports"
    ]
  },
```

**Comment by TrySound** [comment]
Because Babel defined after postcss-loader. Also you need to add css extension to test.
