### ISSUE TITLE
[Docker] No PostCSS Config found

### ISSUE THREAD

**Issue by Pszek** [postcss/postcss-loader#275]
During a build process (with Docker) I stumbled upon the below issue:

```ERROR in /tmp/~/react-virtualized/styles.css
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /tmp/node_modules/react-virtualized
    at /tmp/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>
    at runLoaders (/tmp/node_modules/webpack/lib/NormalModule.js:192:19)
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/tmp/node_modules/postcss-loader/lib/index.js:176:71)
    at <anonymous>
 @ ./js/components/VirtualList/index.js 13:0-39
 @ ./js/components/ProductsList/index.js
 @ ./js/startup/clientGlobals.js
 @ multi ./js/startup/clientGlobals

ERROR in /tmp/~/react-virtualized/styles.css
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /tmp/node_modules/react-virtualized
    at /tmp/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>
    at runLoaders (/tmp/node_modules/webpack/lib/NormalModule.js:192:19)
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/tmp/node_modules/postcss-loader/lib/index.js:176:71)
    at <anonymous>
```

packages versions:
```
"postcss-loader": "^2.0.6",
"react (DOM)": "^15.6.1",
"react-virtualized": "^9.9.0",
"webpack": "^2.6.1"
```

This is the only package in the bundle getting that error. I tried to found similar issues but to no avail. If you have some ideas about causes of that problem or how to solve it please share it with me :) .

**Comment by michael-ciniawsky** [comment]
Please post your `$ tree $PROJECT_ROOT` and  your `postcss.config.js` && `webpack.config.js`

**Comment by Pszek** [comment]
@michael-ciniawsky Thanks, self-answer though.

There wasn't provided the path to a postCSS config file in Webpack. It was only a matter of placing these in Webpack config: 
```
options: {
  config: {
     path: 'postcss.config.js'
  }
}
```
