### ISSUE TITLE
@supports rule breaks the loader

### ISSUE THREAD

**Issue by subblue** [postcss/postcss-loader#277]
Possibly a breaking change recently with handling the `@supports` tag?  
If I add something like this:
```
@supports (contain: strict) {
  .panel {
    contain: strict;
    overflow: visible;
  }
}
```

I then get the error:
```
ERROR in ./node_modules/css-loader?{"sourceMap":true,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./src/app.css
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at eachParent (/Users/tom/projects/lec/node_modules/browserslist/index.js:65:18)
    at getStat (/Users/tom/projects/lec/node_modules/browserslist/index.js:79:12)
    at browserslist (/Users/tom/projects/lec/node_modules/browserslist/index.js:188:15)
    at Browsers.parse (/Users/tom/projects/lec/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/tom/projects/lec/node_modules/autoprefixer/lib/browsers.js:52:30)
    at Supports.prefixer (/Users/tom/projects/lec/node_modules/autoprefixer/lib/supports.js:48:24)
    at Supports.prefixed (/Users/tom/projects/lec/node_modules/autoprefixer/lib/supports.js:93:29)
    at /Users/tom/projects/lec/node_modules/autoprefixer/lib/supports.js:316:39
    at Array.map (native)
    at Supports.add (/Users/tom/projects/lec/node_modules/autoprefixer/lib/supports.js:314:22)
    at Supports.process (/Users/tom/projects/lec/node_modules/autoprefixer/lib/supports.js:339:20)
    at /Users/tom/projects/lec/node_modules/autoprefixer/lib/processor.js:43:37
    at /Users/tom/projects/lec/node_modules/postcss-loader/node_modules/postcss/lib/container.js:292:28
    at /Users/tom/projects/lec/node_modules/postcss-loader/node_modules/postcss/lib/container.js:144:26
 @ ./src/app.css 4:14-136 18:2-22:4 19:20-142
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3002 webpack/hot/dev-server react-hot-loader/patch ./src/app.js
```

My webpack CSS config block is:
```
{
  test: /\.css$/,
  use:  [
    { loader: 'style-loader' },
    { loader: 'css-loader', options: { sourceMap: true, importLoaders: 1 } },
    { loader: 'postcss-loader', options: { sourceMap: true } }
  ],
  exclude: /node_modules/
}
```

Specific package versions:
```
"css-loader": "0.28.4",
"postcss": "6.0.6",
"postcss-browser-reporter": "0.5.0",
"postcss-cssnext": "3.0.2",
"postcss-import": "10.0.0",
"postcss-loader": "2.0.6",
"postcss-reporter": "4.0.0",
"postcss-url": "7.0.0",
"style-loader": "0.18.2",
"webpack": "3.3.0"
```

**Comment by michael-ciniawsky** [comment]
> Module build failed: TypeError: Path must be a string. Received undefined
>  at eachParent (/Users/tom/projects/lec/node_modules/**browserslist**/index.js:65:18)

https://github.com/ai/browserslist/pull/161 :)
