### ISSUE TITLE
Bluebird warnings

### ISSUE THREAD

**Issue by czaarek99** [postcss/postcss-loader#284]
My express application starts with this line ` global.Promise = require("bluebird");`. And when postcss-loader runs bluebird spews out this warning:

`(node:13276) Warning: a promise was created in a handler at C:\Programming\HtmlProjects\Shadow\node_modules\postcss-loader\lib\index.js:173:16 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (C:\Programming\HtmlProjects\Shadow\node_modules\bluebird\js\release\promise.js:79:10)`

The same warning is repeated about 15 times.

**Comment by evilebottnawi** [comment]
@czaarek99 what is version `postcss-loader` your use ? Because on https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L173 line there is no promises which return something

**Comment by czaarek99** [comment]
I'm using version 2.0.6

**Comment by evilebottnawi** [comment]
@czaarek99 can your create minimum reproducible test repo?

**Comment by michael-ciniawsky** [comment]
What's the status here ? Maybe related to #269, but `postcss-loader` won't receive any changes for custom libs unrelated to itself, especially if an ECMA Standard exists

**Comment by czaarek99** [comment]
@michael-ciniawsky Yeah, that's for sure the same issue that I'm having.

**Comment by yizhizailusang** [comment]
I have the same problem，postcss-loader version is "^3.0.0"， how to solve it，thanks~
