### ISSUE TITLE
Plugins object syntax doesn't work

### ISSUE THREAD

**Issue by KidkArolis** [postcss/postcss-loader#391]
I'm not sure specifying plugins as object works as specified in the README, e.g.:

```
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {},
    'cssnano': {}
  }
```

throws

```
Module build failed (from /Users/karolis/projects/jetpack/node_modules/postcss-loader/src/index.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/karolis/projects/jetpack/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/karolis/projects/jetpack/node_modules/postcss/lib/processor.js:54:25)
    at postcss (/Users/karolis/projects/jetpack/node_modules/postcss/lib/postcss.js:73:10)
    at Promise.resolve.then.then (/Users/karolis/projects/jetpack/node_modules/postcss-loader/src/index.js:140:12)
```

**Comment by michael-ciniawsky** [comment]
Did you use this syntax with a `postcss.config.js` file or in the `webpack.config.js` ? The latter does definitely not work...

**Comment by KidkArolis** [comment]
I did this in the webpack.config.js
