### ISSUE TITLE
postcss-loader breaks with mini-css-extract-plugin on !important;

### ISSUE THREAD

**Issue by manniL** [postcss/postcss-loader#392]
Considering the following CSS code:

```css
a {
  border: 1px solid #3060b1;
  border-bottom: 1px solid #3060b1 !important;
}
```

`postcss-loader` will break when used together with `mini-css-extract-plugin`.
If I remove the `!important`, I don't experience any errors anymore.

Related: https://github.com/postcss/postcss-loader/issues/159, https://github.com/nuxt/nuxt.js/issues/3996

### Error (Logs|Stacks)

<details>

```
ERROR in ./assets/sass/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property '0' of undefined
    at /sandbox/assets/sass/app.css:1:1
    at /sandbox/assets/sass/app.css:2:3
    at exports.default.v (/sandbox/node_modules/postcss-merge-longhand/dist/lib/parseTrbl.js:11:14)
    at mergeRedundant (/sandbox/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:144:41)
    at rule.walkDecls.decl (/sandbox/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:460:16)
    at /sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:205:16
    at /sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:131:17)
    at Rule.walkDecls (/sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:203:17)
    at Object.merge (/sandbox/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:10)
    at _decl2.default.forEach.p (/sandbox/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/sandbox/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:239:18
    at /sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:135:18
    at Root.each (/sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/sandbox/node_modules/postcss-loader/node_modules/postcss/lib/container.js:131:17)
    at runLoaders (/sandbox/node_modules/webpack/lib/NormalModule.js:286:20)
    at /sandbox/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /sandbox/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/sandbox/node_modules/postcss-loader/src/index.js:208:9)
    at <anonymous>
 @ ./.nuxt/App.js 3:0-32
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

</details>

### Reproduction (Code)

1. Open the [CodeSandbox](https://codesandbox.io/s/qzx1zl9q5j).
2. Open the server panel on the left
3. Run `yarn build`
4. Check terminal output

### Environment

I'm using Nuxt 2 for reproducing the error (sorry that I couldn't break it down to just webpack + loaders, please ping if that's necessary). PostCSS version 6

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|[name][version]|[version]|[version]|[version]|

**Comment by evilebottnawi** [comment]
@manniL problem in `cssnano`, thanks for issue

**Comment by evilebottnawi** [comment]
Issue https://github.com/cssnano/cssnano/issues/618
