### ISSUE TITLE
Duplicate warnings and/or running twice

### ISSUE THREAD

**Issue by tysonnero** [postcss/postcss-loader#79]
Hi - I am seeing duplicate warnings for both autoprefixer and stylelint. Not sure if this is specific to postcss-loader or postcss itself, but I figured I'd start here. Anyone have an idea how to solve this? Thanks in advance!

From webpack.config:
```
module: {
	loaders: [
		{ test: /\.scss/, loader: ExtractTextPlugin.extract('style', 'css!postcss!sass') },
		{ test: /\.(woff2?|ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file?name=/assets/fonts/[hash].[ext]' },
		{ test: /\.(jpeg|jpeg|gif|png|tiff)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file?name=/assets/images/[hash].[ext]' }
	]
},
plugins: [
	new ExtractTextPlugin('assets/css/[name].min.css')
],
postcss: [
	autoprefixer({ browsers: ['> 5% in US', 'last 2 versions', 'IE 9'] }),
	stylelint(),
	reporter({ clearMessages: true })
]
```

Example output in console:
```
app/assets/styles/default/cards/index.scss
203:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
206:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
213:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
216:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]

app/assets/styles/default/cards/index.scss
203:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
206:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
213:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
216:5   ‼  Expected indentation of 4 spaces (indentation) [stylelint]
```

**Comment by ai** [comment]
Could I ask you to help me a little a create small demo project to reproduce issue?

**Comment by ai** [comment]
No demo project, no help ;).

I think problem is in used reporter — it doesn’t clean `result.warnings()` after output them to CLI.

**Comment by tysonnero** [comment]
@ai My apologies... stylelint became a low priority on the project I was working on, so this was the first time I've looked again at this ticket. 

To note, I totally removed postcss-reporter, and was still seeing duplicate warnings in the console. I've since switched to a webpack plugin called stylelint-webpack-plugin, and duplicate warnings/errors went away.

I'll see if I can create a demo project to replicate when time permits. Thanks!

**Comment by tysonnero** [comment]
@ai I've put a project together that's experiencing the issue: https://github.com/tysonnero/react-webpack-postcss-loader. Just clone it, run npm install, then npm run build or npm run watch. 

There is one error in the SCSS. You should see two duplicate errors reported in the console. You can remove postcss-reporter or autoprefixer from webpack, and the problem will persist.

Thanks!

**Comment by ai** [comment]
Thanks. I try to look it today evening or tomorrow.

**Comment by ai** [comment]
You asked about this warnings?

```
> react-webpack-postcss-loader@1.0.0 build /home/ai/react-webpack-postcss-loader
> webpack --config webpack.config.js --progress --colors

 45% 83/140 build modules
src/components/HelloWorld/HelloWorld.scss
7:15	⚠  Unexpected invalid hex color "#00000" (color-no-invalid-hex) [stylelint]

 69% 178/180 build modules
src/components/HelloWorld/HelloWorld.scss
7:15	⚠  Unexpected invalid hex color "#00000" (color-no-invalid-hex) [stylelint]

Hash: 86a7f4064d10da29a716
```

**Comment by tysonnero** [comment]
@ai 

Yes, those duplicate warnings.  Do you know why they're displaying double?

**Comment by ai** [comment]
@tysonnero this warnings came from `postcss-reporter`, not from loader itself. Seems like it is result of some conflict with webpack output magic.

Maybe we could fix it, but I think using special stylelint loader is better.

Also, maybe console it not a best way for webpack. I think you should:

1. Add linter to Atom.
2. Add linter to `lint-staged` to lint changed files before commit.
3. Add linter to CI.

So you don’t really need linter in webpack loader.

**Comment by tysonnero** [comment]
@ai Thanks for checking on that. I removed postcss-reporter and autoprefixr from the webpack.config and pushed the changes: https://github.com/tysonnero/react-webpack-postcss-loader/commit/934144176cb82958b749b9bfea2ec883e6f3434c.

I am still seeing duplicate warnings in the console. Any thoughts? I'd like to keep the linter in webpack for both JS and CSS for my company's build process. We actually have things we want to fail the build per the whole team

**Comment by ai** [comment]
@tysonnero I pulled changed, run `build` and didn’t get any watnings:

```
➤ npm run build

> react-webpack-postcss-loader@1.0.0 build /home/ai/react-webpack-postcss-loader
> webpack --config webpack.config.js --progress --colors

Hash: 86a7f4064d10da29a716  
Version: webpack 1.13.1
Time: 4028ms
       Asset     Size  Chunks             Chunk Names
js/bundle.js  1.92 MB       0  [emitted]  main
    + 179 hidden modules

ERROR in ./src/index.js

/home/ai/react-webpack-postcss-loader/src/index.js
  1:27  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  2:34  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  3:61  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  4:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

✖ 4 problems (4 errors, 0 warnings)


ERROR in ./src/components/HelloWorld/HelloWorld.js

/home/ai/react-webpack-postcss-loader/src/components/HelloWorld/HelloWorld.js
  1:27   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  2:40   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  3:1    error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  4:43   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  5:13   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  6:117  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  7:4    error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  8:2    error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  9:1    error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

✖ 9 problems (9 errors, 0 warnings)


ERROR in ./~/css-loader?modules&importLoaders=2!./~/sass-loader!./~/postcss-loader!./src/components/HelloWorld/HelloWorld.scss
Module build failed: 
  font-color: #00000;
            ^
      Invalid CSS after "  font-color:": expected expression (e.g. 1px, bold), was "#00000;"
      in /home/ai/react-webpack-postcss-loader/src/components/HelloWorld/HelloWorld.scss (line 7, column 14)
 @ ./src/components/HelloWorld/HelloWorld.scss 4:14-205

ERROR in ./src/components/HelloWorld/HelloWorld.scss
Module build failed: ModuleBuildError: Module build failed: 
  font-color: #00000;
            ^
      Invalid CSS after "  font-color:": expected expression (e.g. 1px, bold), was "#00000;"
      in /home/ai/react-webpack-postcss-loader/src/components/HelloWorld/HelloWorld.scss (line 7, column 14)
    at DependenciesBlock.onModuleBuildFailed (/home/ai/react-webpack-postcss-loader/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/ai/react-webpack-postcss-loader/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/ai/react-webpack-postcss-loader/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/ai/react-webpack-postcss-loader/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/home/ai/react-webpack-postcss-loader/node_modules/sass-loader/index.js:272:13)
    at /home/ai/react-webpack-postcss-loader/node_modules/async/lib/async.js:906:35
    at _arrayEach (/home/ai/react-webpack-postcss-loader/node_modules/async/lib/async.js:85:13)
    at Object.<anonymous> (/home/ai/react-webpack-postcss-loader/node_modules/async/lib/async.js:898:17)
    at Object.callback (/home/ai/react-webpack-postcss-loader/node_modules/async/lib/async.js:44:16)
    at options.error (/home/ai/react-webpack-postcss-loader/node_modules/node-sass/lib/index.js:275:32)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader?modules&importLoaders=2!./~/sass-loader!./~/postcss-loader!./src/components/HelloWorld/HelloWorld.scss
    Module build failed: 
      font-color: #00000;
                ^
          Invalid CSS after "  font-color:": expected expression (e.g. 1px, bold), was "#00000;"
          in /home/ai/react-webpack-postcss-loader/src/components/HelloWorld/HelloWorld.scss (line 7, column 14)
```

**Comment by tysonnero** [comment]
@ai The bottom half is reporting the "font-color: #00000;" warning/error twice. That was the same duplicate warning/error when I had the reporter in.

**Comment by ai** [comment]
Seems like it is ExtractTextPlugin issue :(. Sorry, I am not good in webpack internal parts. I use official API to set a warning.

ExtractTextPlugin has many issues (it is a reason why I came back to Gulp).

**Comment by m-sureshraj** [comment]
@ai @tysonnero 

Very late comment, Hope maybe useful to someone.

Setting { allChunks: true } option in ExtractTextPlugin solve the issue for me.
FYI: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/217
