### ISSUE TITLE
Example config leads to an error (Must install one of: '+libs.join())

### ISSUE THREAD

**Issue by folmert** [postcss/postcss-loader#80]
I merged the example from Usage instructions with my webpack.config.js:

```js
var precss       = require('precss');
var autoprefixer = require('autoprefixer');

module.exports = {
    module:  {
        loaders: [
            {
                test:   /\.css$/,
                loader: "style-loader!css-loader!postcss-loader"
            }
        ]
    },
    entry:   ["./entry.js",
        './analytics.js'
    ],
    output:  {
        filename: "./bundleAnalytics.js"
    },
    watch:   true,
    postcss: function () {
        return [precss, autoprefixer];
    }
};
```

but when I try to run `webpack` it returns:

```
[my project's path]\node_modules\precss\node_modules\postcss-partial-import\node_modules\fs-promise\node_modules\any-promise\any-promise.js:32
  throw new Error('Must install one of: '+libs.join());
        ^
Error: Must install one of: es6-promise,promise,native-promise-only,bluebird,rsvp,when,q
    at [my project's path]\node_modules\precss\node_modules\postcss-partial-import\node_modules\fs-promise\node_modules\any-promise\any-promise.js:32:9
    at Object.<anonymous> ([my project's path]\node_modules\precss\node_modules\postcss-partial-import\node_modules\fs-promise\node_modules\any-promise\any-promise.js:33:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ([my project's path]\node_modules\precss\node_modules\postcss-partial-import\node_modules\fs-promise\index.js:4:12)
    at Module._compile (module.js:456:26)
```

**Comment by ai** [comment]
Please show me `node -v` output?

**Comment by folmert** [comment]
v0.10.26

After running `npm update` the output's still the same, so I assume it's the newest version...?

Installing: `npm install es6-promise` helped me to get rid of this error.

**Comment by ai** [comment]
You should update your node.js. Current version is 6.0 ;).

**Comment by ai** [comment]
`postcss-loder` will compile CSS, that you will use in webpack.

So when you write `require('./some/path/to/style.css')` it will be processed by PostCSS.
