### ISSUE TITLE
Imported less files are not being prefixed

### ISSUE THREAD

**Issue by Dakuan** [postcss/postcss-loader#9]
see https://github.com/Dakuan/postcss-webpack-bug

`bar.less` imports `foo.less`, 

`bar` gets prefixed correctly: https://github.com/Dakuan/postcss-webpack-bug/blob/master/bug.css#L6

but `foo` gets ignored: https://github.com/Dakuan/postcss-webpack-bug/blob/master/bug.css#L2

**Comment by Dakuan** [comment]
It's been suggested to change the order of the loaders to:

```
loader: ExtractTextPlugin.extract("style-loader", "postcss-loader!css-loader!less-loader")
```

but this results in:

```
-> webpack
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.9.7
Time: 399ms
    + 1 hidden modules

ERROR in ./bar.less
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/extract-text-webpack-plugin/loader.js:91:22)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compiler.js:213:10)
    at /Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compiler.js:401:12
    at Tapable.next (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Tapable.next (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Tapable.applyPluginsAsync (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compiler.js:398:9)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compilation.js:555:13)
Child extract-text-webpack-plugin:
        + 2 hidden modules

    ERROR in ./~/postcss-loader!./~/css-loader!./~/less-loader!./bar.less
    /Users/Dom/git/postcss-webpack-bug/node_modules/css-loader/index.js!/Users/Dom/git/postcss-webpack-bug/node_modules/less-loader/index.js!/Users/Dom/git/postcss-webpack-bug/bar.less:1:1: Unknown word
    exports = module.exports = require("./node_modules/css-loader/lib/css-base.js")();
    ^
    exports.push([module.id, ".foo {\n  background-color: red;\n  display: flex;\n}\n.bar {\n  background-color: yellow;\n  display: flex;\n}\n", ""]);

    ERROR in ./~/postcss-loader!./~/css-loader!./~/less-loader!./bar.less
    Module build failed: Error: Final loader didn't return a Buffer or String
        at DependenciesBlock.onModuleBuild (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
        at nextLoader (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
        at /Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
        at context.callback (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
        at /Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/index.js:40:17
        at lib$es6$promise$$internal$$tryCatch (/Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:319:16)
        at lib$es6$promise$$internal$$invokeCallback (/Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:331:17)
        at /Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:876:13
        at Object.lib$es6$promise$asap$$flush [as _onImmediate] (/Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:113:9)
        at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by ai** [comment]
Sorry, I will have time to see only on next week.

Right now, try to remove `less` or `postcss` loader to see, who is a source.

**Comment by Dakuan** [comment]
```
loader: ExtractTextPlugin.extract("style-loader", "css-loader!less-loader")
```

works, but obviously does not prefix files:

```
.foo {
  background-color: red;
  display: flex;
}
.bar {
  background-color: yellow;
  display: flex;
}
```

```
loader: ExtractTextPlugin.extract("style-loader", "postcss-loader!css-loader")
```
errors
```
 -> webpack
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.9.7
Time: 173ms
    + 1 hidden modules

ERROR in ./bar.less
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/extract-text-webpack-plugin/loader.js:91:22)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compiler.js:213:10)
    at /Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compiler.js:401:12
    at Tapable.next (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Tapable.next (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Tapable.applyPluginsAsync (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compiler.js:398:9)
    at Tapable.<anonymous> (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/lib/Compilation.js:555:13)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/postcss-loader!./~/css-loader!./bar.less
    /Users/Dom/git/postcss-webpack-bug/node_modules/css-loader/index.js!/Users/Dom/git/postcss-webpack-bug/bar.less:1:1: Unknown word
    exports = module.exports = require("./node_modules/css-loader/lib/css-base.js")();
    ^
    exports.i(require("-!./node_modules/css-loader/index.js!./foo"), "");

    ERROR in ./~/postcss-loader!./~/css-loader!./bar.less
    Module build failed: Error: Final loader didn't return a Buffer or String
        at DependenciesBlock.onModuleBuild (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
        at nextLoader (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
        at /Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
        at context.callback (/Users/Dom/git/postcss-webpack-bug/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
        at /Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/index.js:40:17
        at lib$es6$promise$$internal$$tryCatch (/Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:319:16)
        at lib$es6$promise$$internal$$invokeCallback (/Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:331:17)
        at /Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:876:13
        at Object.lib$es6$promise$asap$$flush [as _onImmediate] (/Users/Dom/git/postcss-webpack-bug/node_modules/postcss-loader/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:113:9)
        at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by ai** [comment]
@lydell maybe you can help me here? I think you know webpack better as author of `autoprefixer-loader`.

**Comment by lydell** [comment]
I think you confused `autoprefixer-loader` with `autoprefixer-brunch` :) `autoprefixer-loader` is written by @passy.

**Comment by ai** [comment]
Oops :). Yeap @passy maybe you can help me here, because you know webpack better as author of `autoprefixer-loader`?

**Comment by badsyntax** [comment]
As I understand it, you need to pipe the output of the compiled css into the css-loader. Thus, this should be the correct order: 

```js
ExtractTextPlugin.extract("style-loader", "css-loader!postcss-loader!less-loader")
```

**Comment by ai** [comment]
@Dakuan does @badsyntax fix helps?

**Comment by passy** [comment]
@ai Sorry, I'm not sure what's happening here and I'm not really a great person to ask about webpack. Except for maintaining `autoprefixer-loader` I don't have any webpack-related projects at the moment. :(

**Comment by Dakuan** [comment]
@ai worked a charm!

**Comment by avindra** [comment]
Thanks @badsyntax  that order works. Can you explain why this works? It seems really unintuitive that postcss-loader is right in the middle. 

I would think that postcss-loader should appear at the end as it is the last step...

**Comment by Dakuan** [comment]
@avindra that was the source of my head banging. Made sense for the final step to be at either end of the chain, but not the middle!

**Comment by badsyntax** [comment]
@avindra @Dakuan 

It's been a while since I've used webpack and i'd be damned if I knew the point of these loaders anymore. I hate you so much webpack.

css-loader expects CSS code, there's nothing more to it than that. pass in your final compiled CSS into css-loader. 

I guess the output of css-loader is not a stream of CSS, thus you can't pipe that ouput into postcss-loader. 

* style-loader|css-loader is the way to do it just with css
* style-loader|css-loader|less-loader is the way to do it if you want to use less
* style-loader|css-loader|postcss-loader|less-loader is the way to post-process the compiled less (css)

**Comment by MatTheCat** [comment]
Doesn't work for me when I run `webpack -p`:

```javascript
ExtractTextPlugin.extract("style", "css!postcss!less")
```

Am I missing something?

**Comment by avindra** [comment]
@MatTheCat : looks like you're missing "-loader" from your loaders... unless you're using some special webpack config to eliminate those suffixes :-)

@badsyntax : the loaders are kind of like black magic. I've yet to come across good technical documentation on how it works.  Out of curiosity - in terms of big module bundling systems (i.e, webpack, browserify, jspm), which do you like the most?

**Comment by MatTheCat** [comment]
@avindra well I don't know but I'm sure it doesn't change anything.

**Comment by MatTheCat** [comment]
My apologies, I didn't know css-loader run autoprefixer to remove prefixes when using  `--optimize-minimize`. So postcss-loader added prefixes and css-loader removed them. :persevere:
